"""Initial migration

Revision ID: 197f9a0a06d3
Revises: 
Create Date: 2025-10-08 01:12:02.925273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197f9a0a06d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('check_in_date', sa.DateTime(), nullable=False),
    sa.Column('check_out_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_hotels_admin_id_admins')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('hotel_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('amenity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_hotel_amenities_amenity_id_amenities')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_hotel_amenities_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'amenity_id', name='unique_hotel_amenity')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_rooms_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_rooms_room_type_id_room_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_rooms',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booked_rooms_booking_id_bookings')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_booked_rooms_room_id_rooms')),
    sa.PrimaryKeyConstraint('booking_id', 'room_id')
    )
    op.drop_table('birds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('species', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='birds_pkey')
    )
    op.drop_table('booked_rooms')
    op.drop_table('rooms')
    op.drop_table('hotel_amenities')
    op.drop_table('hotels')
    op.drop_table('bookings')
    op.drop_table('room_types')
    op.drop_table('guests')
    op.drop_table('amenities')
    op.drop_table('admins')
    # ### end Alembic commands ###
