"""Make admin name unique

Revision ID: 5ff6a028a0b1
Revises: e107712b6c58
Create Date: 2025-09-30 18:28:51.922474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff6a028a0b1'
down_revision = 'e107712b6c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_admin_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint("uq_admin_name", type_='unique')

    # ### end Alembic commands ###
