"""Add uniqueness to fields in hotels table

Revision ID: ad62145b6475
Revises: ce20305d0cbb
Create Date: 2025-10-05 23:45:02.815826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad62145b6475'
down_revision = 'ce20305d0cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_hotels_email', ['email'])
        batch_op.create_unique_constraint('uq_hotels_name', ['name'])
        batch_op.create_unique_constraint('uq_hotels_address', ['address'])
        batch_op.create_unique_constraint('uq_hotels_phone', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
