"""Remove hotel_id ForeignKey from admins

Revision ID: bc28ccfe75a5
Revises: 9b5389c0a044
Create Date: 2025-10-05 02:10:00.801417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc28ccfe75a5'
down_revision = '9b5389c0a044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('fk_admins_hotel_id_hotels', type_='foreignkey')
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_admins_hotel_id_hotels', 'hotels', ['hotel_id'], ['id'])

    # ### end Alembic commands ###
