"""Add BookedRoom join table and it's relationships

Revision ID: e107712b6c58
Revises: 95548db15c88
Create Date: 2025-09-26 19:44:53.858506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e107712b6c58'
down_revision = '95548db15c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_rooms',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booked_rooms_booking_id_bookings')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_booked_rooms_room_id_rooms')),
    sa.PrimaryKeyConstraint('booking_id', 'room_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_room_id_rooms', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('room_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_room_id_rooms', 'rooms', ['room_id'], ['id'])

    op.drop_table('booked_rooms')
    # ### end Alembic commands ###
